### PR TITLE
Fix issue when the modal is closed other than by using the add button

### LINKED ISSUE #148: Closing a window to create a new item breaks item editing
If I hit the X in the corner instead of saving (say because I noticed a typo), I can't add new items anymore until I leave the page

### PR DESCRIPTION
**Pull request by cmfcmf**
I know the JavaScript file isn't getting more readable - but I also don't want to spend too much time if all of it eventually goes away due to a new frontend.
closes #148

### CODE REVIEW

**Comment by harkenn** [comment]
Travis build failed, looks like browser tests that need to be updated?

**Comment by cmfcmf** [comment]
Yeah, noticed it as well. I'm trying to figure out why. They fail with the same error that also came up a few times on the production site: 
> Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function setIsUnique() on null"

**Comment by harkenn** [comment]
That's...odd, I thought I was reviewing a different card. Ignore the approval ^

**Comment by cmfcmf** [comment]
Okay. Feel free to review this though, I fixed the test failures.

**Comment by harkenn** [comment]
Oh ok then you're good to go. Everything else was good aside from the build.

**Pull request merged**
