### PR TITLE
Footer design

### LINKED ISSUE #321: Improve page footer design
The footer looks off, mainly because the text is directly on top of the gray page background. 
The obvious solution would be to also give it a white background like the other content containers, but I feel like that would be distracting.
Maybe we could give it a dark background (like the search filters) that spans the entire width of the page?
Not sure about what's best. If you have any ideas, leave them below :point_down:

### PR DESCRIPTION
**Pull request by wetterlicht**
Closes #321 

My attempt at improving the footer design using existing adl colors. Admittedly not my strong suit :)

<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/349"></a>

### CODE REVIEW

**Comment by Wigginns** [comment]
Colors look good. Going to leave another comment talking about the content on paragraph 1 because it's outdated.

**Comment by cmfcmf** [comment]
I like the size of the margin.

> The content on paragraph 1 needs some revision and this could happen here (imo). I would suggest removing the link talking about "apply to be a curator here" as the link is to a now archived reddit post. Perhaps we should just direct people to discord?

See also #131 for more discussion on this topic. I'm not sure whether we should direct people to discord, but also don't really have a better idea.

**Comment by Wigginns** [comment]
Yeah. I’m not really sure how to manage the “who” part either. As you mentioned, a rogue curator could do some real damage and we don’t really know what the fix would take

**Comment by cmfcmf** [comment]
Maybe we should remove the sentence about curators until we have a definitive idea (that can be discussed in #131)?

**Pull request merged**
