### PR TITLE
Clear All Filters Button

### LINKED ISSUE #340: Clear all filters button
Would be nice to have a "clear all" button for removing filters. Probably should only show up if there is more than one selected

### PR DESCRIPTION
**Pull request by wetterlicht**
Closes #340 

<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/346"></a>

<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/346"></a>

### CODE REVIEW

**Comment by Wigginns** [comment]
This works great though I’m too unfamiliar with react to really comment on code or spot potential issues 😅

**Comment by wetterlicht** [comment]
I'm also not overly familiar with react, so this was mostly focused on making it work rather than doing so elegantly.
And yes, checking if a filter is set feels pretty messy atm, glad this well improve soon.

**Comment by cmfcmf** [comment]
Is there

**Comment by cmfcmf** [comment]
> @cmfcmf closed this 1 minute ago
> @cmfcmf reopened this 1 minute ago

Whoops, I misclicked.

Is there anything else you want to do with this PR (I'm asking because it is still labelled as draft)?

**Comment by wetterlicht** [comment]
No, just made it a draft because I wasn't sure if all this was the React way of doing it :)

**Comment by cmfcmf** [comment]
> No, just made it a draft because I wasn't sure if all this was the React way of doing it :)

I see! To me, a pull request that is marked as a draft suggests that the author still intends to push further changes. You don't have to mark your PR as a draft when you're unsure whether what you did is right or the best way to do it - reviewers will likely give that kind of feedback :+1:

**Pull request merged**
