### PR TITLE
Change /adventures/new route to /adventure

### PR DESCRIPTION
**Pull request by cmfcmf**
Currently, if you create an adventure called 'new', the adventure's show route would be `/adventures/new`, which is the same as the route to create a new adventure. This would result in the adventure called 'new' not being possible to access. This PR changes the route to create new adventures to `/adventure`.
It also fixes a Typo I noticed.

### CODE REVIEW

**Comment by cmfcmf** [comment]
> According to most standards, new adventure should be Post to /adventures or /adventure

If we POSTed to `/adventures`, this would work, but the creation form needs a GET route - which cannot be `/adventures`, as that's where the list of adventures is at. I would go for `/adventure` for both GET and POST then, okay?

**Comment by harkenn** [comment]
So:
`GET /adventures` - all adventures listed
`GET /adventure/{someAdventure}` - display specific adventure
`GET /adventure` - display new adventure form
`POST /adventure` - submit new adventure
?

**Comment by cmfcmf** [comment]
Yeah, if you think that's alright 👍

**Comment by harkenn** [comment]
That is a good pattern, yes.

**Comment by cmfcmf** [comment]
Done - this should be good to go once the tests run through.

**Comment by cmfcmf** [comment]
> Just to be double sure, this won't change the URL on production to adventurelookup.com/adventures/adventures right? That would be bad....

Uhhm, I don't think so 😄 Why should it? Also, the tests run through fine (they use /adventures) and we will be able to verify on the dev server.

**Comment by harkenn** [comment]
Well the route previously was `/` but on production if you try to go to `adventurelookup.com` it redirects you to `adventurelookup.com/adventures` so...the logical conclusion is that its going to be `adventurelookup.com/adventures/adventures` after this change since you're changing the route from `/` to `/adventures`.

**Pull request merged**
