### PR TITLE
Improve layout of the adventure details page

### LINKED ISSUE #322: Improve layout of the adventure details page
IMHO the change requests should become their own separate box like the reviews box. Here's a quick mockup of what I mean (ignore the weird spacing, this is just to visualize the three white boxes and their order):

image

The title of the change requests box should have the same formatting as the title of the reviews box, of course.
As a bonus, it would be great if the white margin to the left and right of the blue and green boxes could also be removed.

What do you think about this idea?

### PR DESCRIPTION
**Pull request by wetterlicht**
Closes #322 

Change requests are in a separate, collapsible container which is expanded per default. In order to use Bootstraps collapse functionality I had to update jquery from 3.5 to 3.5.1.

<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/351"></a>

### CODE REVIEW

**Comment by wetterlicht** [comment]
I think switching the order would be a good change for most users.

**Comment by cmfcmf** [comment]
I didn't have time to review this yet, but I have an opinion on the order of things:

> in theory, more users probably are interested in the reviews than the change requests and the change requests section can get quite long if there are many on the same adventure.

I would argue that the opposite is true. IMHO unresolved change requests should be displayed prominently, because users might otherwise only see incomplete or wrong data and never scroll down far enough to see change requests.

**Comment by Wigginns** [comment]
Either way, I like the collapsible aspect you've added here. I'd be completely fine with leaving it, just thought I'd throw the suggestion out there. As an aside, this is exactly the sort of thing that having user interaction data would be great for. Again, maybe overkill but it could be interesting nonetheless.

**Comment by wetterlicht** [comment]
As always, thanks for the feedback! :)

**Pull request merged**
