### PR TITLE
Issue 320 click on tags

### PR DESCRIPTION
**Pull request by damienBAUDET**
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/350"></a>

### CODE REVIEW

**Comment by Wigginns** [comment]
Something weird going on with the functional tests. I can't see how your changes would effect these tests

**Comment by cmfcmf** [comment]
> Something weird going on with the functional tests. I can't see how your changes would effect these tests.

I fixed the issue in c9af974. The problem was with this:

```twig
{{ macros.search('edition', adventure.edition.name)|default('Unknown Edition') }}
```
`adventure.edition` can be `null`, which results in an error if you try to access `.name` on it.

**Comment by damienBAUDET** [comment]
👌

**Comment by Wigginns** [comment]
I should have caught that.  I'd done the exact same thing when I was fiddling with this issue last weekend 🤦‍♂️

**Pull request merged**
