### PR TITLE
Style adventure cards

### PR DESCRIPTION
**Pull request by jsaugustyn**
Reworked how adventure cards are displayed on the home page. Specifically:

- Added a snippet of the adventure description to each card. As a DM, I would like to be able to quickly browse and see if an adventure sounds interesting before taking the time to click through to the detail page. The code is pretty hacky, as I had to deduce the structure of the `adventure.info` field. Ultimately, I think the description ought to get its own named field in the model. Also, there is probably a better way to get a snippet from the description. I just grabbed the first 250 characters.
- Simplified the meta info display and redid the layout for better usability. Key information fields now have icons to assist visual scanning. 
- Dropped "publisher" as I don't think most DMs care enough about this for it to be on the home page.
- Added max level and combined it with min level, so now you can easily see the range.

### CODE REVIEW

**Comment by harkenn** [comment]
This shouldn't have been merged in. It involves over a thousand files that should have been git ignored. If this is to be a collaborative effort, there needs to be the opportunity to review and provide feedback before prs are merged.

**Comment by harkenn** [comment]
There was also a conversion from tabs to spaces or spaces to tabs, making it difficult to see what was legitimately changed and what was an indentation change

**Comment by JohnnyFlash** [comment]
That's a reasonable statement....  I got a little over zealous.
I'll revert the merge.

-Jerry

**Comment by harkenn** [comment]
No worries, thanks Jerry. I'll do a review to mark what needs to be fixed

**Comment by harkenn** [comment]
@JohnnyFlash When you reverted, did you use the "Revert" button from this PR? 

image

**Comment by harkenn** [comment]
So @JohnnyFlash it looks like the vagrant directory wasn't added this commit; just several files of it changed. I'll submit a PR that removes the directory appropriately. For now I'm reverting your reversion in order to put this code back in.

**Comment by JohnnyFlash** [comment]
Yes... OK.

**Comment by jsaugustyn** [comment]
I'm not sure what those 1,000 files were. This pull request only touched
three files:

   - app/Resources/views/adventure/index.html.twig
   - app/Resources/views/base.html.twig
   - app/Resources/webpack/style.scss

Where did you see over a thousand different files?

**Comment by harkenn** [comment]
I think I looked at the changes diff, which resulted in over a 1000 lines added because it included the composer stuff. I was looking on mobile though so I just read it wrong. In any case this has been merged in and I've fixed the `.vagrant` stuff in a separate PR.

**Comment by jsaugustyn** [comment]
Ha, that would do it! Good call to move the vagrant stuff to gitignore.

**Pull request merged**
